- name: Ensure wazuh_admin_password secret exists
  shell: |
    set -e
    if ! docker secret ls --format '{{"{{"}}.Name{{"}}"}}' | grep -q '^wazuh_admin_password$'; then
      echo "Missing Swarm secret 'wazuh_admin_password'"
      exit 2
    fi
  register: secret_check
  failed_when: secret_check.rc != 0 and secret_check.rc != 2
  changed_when: false
